name: apparmor_prompt
description: "A Flutter UI for apparmor prompting."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=3.22.2"

dependencies:
  apparmor_prompting_client: ^1.0.0
  args: ^2.5.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  riverpod_annotation: ^2.3.5
  ubuntu_lints: ^0.4.0
  ubuntu_logger: ^0.1.1
  ubuntu_service: ^0.3.2
  url_launcher: ^6.3.0
  yaru:
    git:
      url: https://github.com/ubuntu/yaru.dart.git
      ref: main
  yaru_widgets: ^1.1.2

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
